/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VenteTerrainsRouteImport } from './routes/vente.terrains'
import { Route as VenteMaisonsRouteImport } from './routes/vente.maisons'
import { Route as VenteTerrainIdRouteImport } from './routes/vente-terrain.$id'
import { Route as VenteMaisonIdRouteImport } from './routes/vente-maison.$id'
import { Route as LocationSaisonniereRouteImport } from './routes/location.saisonniere'
import { Route as LocationAnnuelleRouteImport } from './routes/location.annuelle'
import { Route as LocationSaisonniereIdRouteImport } from './routes/location-saisonniere.$id'
import { Route as LocationAnnuelleIdRouteImport } from './routes/location-annuelle.$id'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VenteTerrainsRoute = VenteTerrainsRouteImport.update({
  id: '/vente/terrains',
  path: '/vente/terrains',
  getParentRoute: () => rootRouteImport,
} as any)
const VenteMaisonsRoute = VenteMaisonsRouteImport.update({
  id: '/vente/maisons',
  path: '/vente/maisons',
  getParentRoute: () => rootRouteImport,
} as any)
const VenteTerrainIdRoute = VenteTerrainIdRouteImport.update({
  id: '/vente-terrain/$id',
  path: '/vente-terrain/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const VenteMaisonIdRoute = VenteMaisonIdRouteImport.update({
  id: '/vente-maison/$id',
  path: '/vente-maison/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationSaisonniereRoute = LocationSaisonniereRouteImport.update({
  id: '/location/saisonniere',
  path: '/location/saisonniere',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationAnnuelleRoute = LocationAnnuelleRouteImport.update({
  id: '/location/annuelle',
  path: '/location/annuelle',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationSaisonniereIdRoute = LocationSaisonniereIdRouteImport.update({
  id: '/location-saisonniere/$id',
  path: '/location-saisonniere/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationAnnuelleIdRoute = LocationAnnuelleIdRouteImport.update({
  id: '/location-annuelle/$id',
  path: '/location-annuelle/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/location-annuelle/$id': typeof LocationAnnuelleIdRoute
  '/location-saisonniere/$id': typeof LocationSaisonniereIdRoute
  '/location/annuelle': typeof LocationAnnuelleRoute
  '/location/saisonniere': typeof LocationSaisonniereRoute
  '/vente-maison/$id': typeof VenteMaisonIdRoute
  '/vente-terrain/$id': typeof VenteTerrainIdRoute
  '/vente/maisons': typeof VenteMaisonsRoute
  '/vente/terrains': typeof VenteTerrainsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/location-annuelle/$id': typeof LocationAnnuelleIdRoute
  '/location-saisonniere/$id': typeof LocationSaisonniereIdRoute
  '/location/annuelle': typeof LocationAnnuelleRoute
  '/location/saisonniere': typeof LocationSaisonniereRoute
  '/vente-maison/$id': typeof VenteMaisonIdRoute
  '/vente-terrain/$id': typeof VenteTerrainIdRoute
  '/vente/maisons': typeof VenteMaisonsRoute
  '/vente/terrains': typeof VenteTerrainsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/location-annuelle/$id': typeof LocationAnnuelleIdRoute
  '/location-saisonniere/$id': typeof LocationSaisonniereIdRoute
  '/location/annuelle': typeof LocationAnnuelleRoute
  '/location/saisonniere': typeof LocationSaisonniereRoute
  '/vente-maison/$id': typeof VenteMaisonIdRoute
  '/vente-terrain/$id': typeof VenteTerrainIdRoute
  '/vente/maisons': typeof VenteMaisonsRoute
  '/vente/terrains': typeof VenteTerrainsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/contact'
    | '/location-annuelle/$id'
    | '/location-saisonniere/$id'
    | '/location/annuelle'
    | '/location/saisonniere'
    | '/vente-maison/$id'
    | '/vente-terrain/$id'
    | '/vente/maisons'
    | '/vente/terrains'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/contact'
    | '/location-annuelle/$id'
    | '/location-saisonniere/$id'
    | '/location/annuelle'
    | '/location/saisonniere'
    | '/vente-maison/$id'
    | '/vente-terrain/$id'
    | '/vente/maisons'
    | '/vente/terrains'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/contact'
    | '/location-annuelle/$id'
    | '/location-saisonniere/$id'
    | '/location/annuelle'
    | '/location/saisonniere'
    | '/vente-maison/$id'
    | '/vente-terrain/$id'
    | '/vente/maisons'
    | '/vente/terrains'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  ContactRoute: typeof ContactRoute
  LocationAnnuelleIdRoute: typeof LocationAnnuelleIdRoute
  LocationSaisonniereIdRoute: typeof LocationSaisonniereIdRoute
  LocationAnnuelleRoute: typeof LocationAnnuelleRoute
  LocationSaisonniereRoute: typeof LocationSaisonniereRoute
  VenteMaisonIdRoute: typeof VenteMaisonIdRoute
  VenteTerrainIdRoute: typeof VenteTerrainIdRoute
  VenteMaisonsRoute: typeof VenteMaisonsRoute
  VenteTerrainsRoute: typeof VenteTerrainsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vente/terrains': {
      id: '/vente/terrains'
      path: '/vente/terrains'
      fullPath: '/vente/terrains'
      preLoaderRoute: typeof VenteTerrainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vente/maisons': {
      id: '/vente/maisons'
      path: '/vente/maisons'
      fullPath: '/vente/maisons'
      preLoaderRoute: typeof VenteMaisonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vente-terrain/$id': {
      id: '/vente-terrain/$id'
      path: '/vente-terrain/$id'
      fullPath: '/vente-terrain/$id'
      preLoaderRoute: typeof VenteTerrainIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vente-maison/$id': {
      id: '/vente-maison/$id'
      path: '/vente-maison/$id'
      fullPath: '/vente-maison/$id'
      preLoaderRoute: typeof VenteMaisonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location/saisonniere': {
      id: '/location/saisonniere'
      path: '/location/saisonniere'
      fullPath: '/location/saisonniere'
      preLoaderRoute: typeof LocationSaisonniereRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location/annuelle': {
      id: '/location/annuelle'
      path: '/location/annuelle'
      fullPath: '/location/annuelle'
      preLoaderRoute: typeof LocationAnnuelleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location-saisonniere/$id': {
      id: '/location-saisonniere/$id'
      path: '/location-saisonniere/$id'
      fullPath: '/location-saisonniere/$id'
      preLoaderRoute: typeof LocationSaisonniereIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location-annuelle/$id': {
      id: '/location-annuelle/$id'
      path: '/location-annuelle/$id'
      fullPath: '/location-annuelle/$id'
      preLoaderRoute: typeof LocationAnnuelleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  ContactRoute: ContactRoute,
  LocationAnnuelleIdRoute: LocationAnnuelleIdRoute,
  LocationSaisonniereIdRoute: LocationSaisonniereIdRoute,
  LocationAnnuelleRoute: LocationAnnuelleRoute,
  LocationSaisonniereRoute: LocationSaisonniereRoute,
  VenteMaisonIdRoute: VenteMaisonIdRoute,
  VenteTerrainIdRoute: VenteTerrainIdRoute,
  VenteMaisonsRoute: VenteMaisonsRoute,
  VenteTerrainsRoute: VenteTerrainsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
